// GENERATED by tools/ondevice-model/build-model.mjs (v1, modelClass `ondevice-fwd-v1`).
export { FRAME_KERNEL_WASM_B64, FRAME_KERNEL_SHA256 } from './frame-kernel.wasm.js';
export { WEIGHTS_BIN_B64, WEIGHTS_FRAME_COUNT, WEIGHTS_SHA256 } from './weights.bin.js';
