// E1-T07 · EES §4 event table — append-only registry (data only; registry-purity enforced).
// One row per concrete v1 event type from the locked EES §4 table (31 types; the three
// v2-reserved types — RuleCreated, RemoteEventsApplied, DeviceRegistered — are intentionally
// NOT declared: they freeze at the Tier-4 harness).
// Field kinds: id | string | number | boolean | primitive | id[] | string[] | record | record[].
// '?' suffix = optional. Append-only law: rows may only be added; edits need an ADR note (A-09).
export const EVENT_REGISTRY = {
  TabObserved: {
    schemaV: 1,
    producer: 'Ingest',
    consumers: ['TabsView', 'ArchiveCounts', 'SearchIndex'],
    idempotentBy: 'ledgeTabId',
    fields: {
      ledgeTabId: 'id',
      browserTabId: 'number',
      windowId: 'number',
      'groupId?': 'number',
      url: 'string',
      urlCanon: 'string',
      canonRulesV: 'number',
      title: 'string',
      domain: 'string',
      ts: 'number',
    },
  },
  TabUpdated: {
    schemaV: 1,
    producer: 'Ingest',
    consumers: ['TabsView', 'SearchIndex', 'MemoryTriggers'],
    idempotentBy: null,
    fields: { ledgeTabId: 'id', changes: 'record' },
  },
  TabActivatedObserved: {
    schemaV: 1,
    producer: 'Ingest',
    consumers: ['Recency', 'NudgeModel'],
    idempotentBy: null,
    fields: { ledgeTabId: 'id', ts: 'number' },
  },
  TabClosedExternal: {
    schemaV: 1,
    producer: 'Ingest',
    consumers: ['RecentlyClosedView', 'DupeIndex'],
    idempotentBy: null,
    fields: { ledgeTabId: 'id', closedAt: 'number', 'lastMissionId?': 'id', 'snapshotRef?': 'id' },
  },
  WindowClosedExternal: {
    schemaV: 1,
    producer: 'Ingest',
    consumers: ['MissionsView'],
    idempotentBy: null,
    fields: { windowId: 'number', 'missionId?': 'id', closedAt: 'number' },
  },
  GroupChanged: {
    schemaV: 1,
    producer: 'Ingest',
    consumers: ['MissionsView'],
    idempotentBy: null,
    fields: { groupId: 'number', 'name?': 'string', 'color?': 'string', 'collapsed?': 'boolean' },
  },
  MissionFormed: {
    schemaV: 1,
    producer: 'UseCases',
    consumers: ['MissionsView', 'Archive'],
    idempotentBy: 'missionId',
    fields: {
      missionId: 'id',
      name: 'string',
      namedBy: 'string',
      tabIds: 'id[]',
      'provenance?': 'string',
    },
  },
  MissionRenamed: {
    schemaV: 1,
    producer: 'UseCases',
    consumers: ['MissionsView', 'SearchIndex'],
    idempotentBy: null,
    fields: { missionId: 'id', name: 'string', namedBy: 'string', 'correctedFrom?': 'string' },
  },
  TabAssigned: {
    schemaV: 1,
    producer: 'UseCases',
    consumers: ['MissionsView', 'TabsView'],
    idempotentBy: null,
    fields: { tabId: 'id', missionId: 'id' },
  },
  TabMoved: {
    schemaV: 1,
    producer: 'UseCases',
    consumers: ['MissionsView', 'TabsView'],
    idempotentBy: null,
    fields: { tabId: 'id', missionId: 'id', 'fromMissionId?': 'id' },
  },
  SnapshotTaken: {
    schemaV: 1,
    producer: 'Snapshot services',
    consumers: ['SessionsView', 'Recovery'],
    idempotentBy: null,
    fields: {
      snapshotId: 'id',
      missionId: 'id',
      partCount: 'number',
      tabRecordRefs: 'id[]',
      groupStyles: 'record[]',
      takenAt: 'number',
      // E2-T08: §5 sessions-row trigger vocabulary; additive-optional in v1
      // construction (builders always emit it; absent on hand-written fixtures
      // and materialized as ABSENT, never fabricated).
      'trigger?': 'string',
    },
  },
  ParkIntentAccepted: {
    schemaV: 1,
    producer: 'Park use cases',
    consumers: ['IntentLedger', 'Recovery'],
    idempotentBy: 'intentId',
    fields: { intentId: 'id', scope: 'record', issuedAt: 'number' },
  },
  TabsParked: {
    schemaV: 1,
    producer: 'Park executor',
    consumers: ['MissionsView', 'ArchiveCounts'],
    idempotentBy: 'intentId',
    fields: { intentId: 'id', secured: 'number', 'failedRefs?': 'record[]' },
  },
  ParkAborted: {
    schemaV: 1,
    producer: 'Park executor',
    consumers: ['IntentLedger', 'Guardian'],
    idempotentBy: 'intentId',
    fields: { intentId: 'id', reason: 'string', liveLeftOpen: 'number' },
  },
  ResumeAccepted: {
    schemaV: 1,
    producer: 'Resume',
    consumers: ['MissionsView', 'Intents'],
    idempotentBy: null,
    fields: {
      missionId: 'id',
      mode: 'string',
      restoredMapping: 'record',
      'movedRefs?': 'record[]',
    },
  },
  MissionResumed: {
    schemaV: 1,
    producer: 'Resume',
    consumers: ['MissionsView', 'Intents'],
    idempotentBy: null,
    fields: {
      missionId: 'id',
      mode: 'string',
      restoredMapping: 'record',
      'movedRefs?': 'record[]',
    },
  },
  RestoreAccepted: {
    schemaV: 1,
    producer: 'Resume variants',
    consumers: ['MissionsView', 'Intents'],
    idempotentBy: null,
    fields: {
      missionId: 'id',
      mode: 'string',
      restoredMapping: 'record',
      'movedRefs?': 'record[]',
    },
  },
  MissionArchived: {
    schemaV: 1,
    producer: 'UseCases',
    consumers: ['ArchiveView', 'MemoryJobs'],
    idempotentBy: null,
    fields: { missionId: 'id' },
  },
  MissionConcluded: {
    schemaV: 1,
    producer: 'UseCases',
    consumers: ['ArchiveView', 'MemoryJobs'],
    idempotentBy: null,
    fields: { missionId: 'id', 'outcomeNote?': 'string', 'concludedAt?': 'number' },
  },
  EntityTrashed: {
    schemaV: 1,
    producer: 'Delete',
    consumers: ['TrashView', 'PurgeChains'],
    idempotentBy: null,
    fields: {
      kind: 'string',
      id: 'id',
      inverseAtom: 'record',
      'bulkId?': 'id',
      deletedAt: 'number',
    },
  },
  TrashRestored: {
    schemaV: 1,
    producer: 'Restore',
    consumers: ['*(all views)'],
    idempotentBy: null,
    fields: { kind: 'string', id: 'id', resolvedMissionId: 'id' },
  },
  TrashPurged: {
    schemaV: 1,
    producer: 'Sweeper',
    consumers: ['PurgeChains', 'Journal'],
    idempotentBy: null,
    fields: { kind: 'string', id: 'id', purgedAt: 'number', purgeEpoch: 'number' },
  },
  MemoryArtifactWritten: {
    schemaV: 1,
    producer: 'Memory application',
    consumers: ['MemoryView', 'MissionsView', 'SearchIndex'],
    idempotentBy: null,
    fields: {
      artifactId: 'id',
      subjectId: 'id',
      kind: 'string',
      value: 'string',
      confidence: 'number',
      provider: 'string',
      modelClass: 'string',
      schemaV: 'number',
      derivedFromSeqRange: 'record',
      // E8-T04 additive (A-09 note: docs/adr-notes/e8-summaries-v1.md) — Spec
      // §6.3 thread narrative rides the same artifact; one-liner stays `value`.
      'thread?': 'string',
    },
  },
  MemoryArtifactInvalidated: {
    schemaV: 1,
    producer: 'Corrections',
    consumers: ['MemoryView', 'MissionsView', 'SearchIndex'],
    idempotentBy: null,
    fields: { artifactId: 'id', cause: 'string' },
  },
  MemoryWiped: {
    schemaV: 1,
    producer: 'ForgetEverything',
    consumers: ['MemoryView'],
    idempotentBy: 'wipeId',
    fields: { purgedCount: 'number', wipeId: 'id' },
  },
  ImportPreviewed: {
    schemaV: 1,
    producer: 'Importers',
    consumers: ['(transient surface only)'],
    idempotentBy: null,
    fields: { previewId: 'id', modelSummary: 'string' },
  },
  ImportCommitted: {
    schemaV: 1,
    producer: 'Import commit',
    consumers: ['*(all views)'],
    idempotentBy: 'batchId',
    fields: {
      batchId: 'id',
      batchManifestRef: 'record',
      source: 'string',
      dupesMode: 'string',
      canonRulesV: 'number',
    },
  },
  ExportCompleted: {
    schemaV: 1,
    producer: 'Exporters',
    consumers: ['(audit feed)'],
    idempotentBy: null,
    fields: { exportId: 'id', scope: 'string', formats: 'string[]', manifestChecksum: 'string' },
  },
  SettingsChanged: {
    schemaV: 1,
    producer: 'Policy',
    consumers: ['*(fan-out hint; ADR-035: settings are not journal-derived truth)'],
    idempotentBy: null,
    fields: { key: 'string', value: 'primitive', schemaV: 'number' },
  },
  SnapshotReconciled: {
    schemaV: 1,
    producer: 'Recovery',
    consumers: ['Recovery', 'Views'],
    idempotentBy: null,
    fields: { basisSeq: 'number', capturedProjectionHash: 'string', scopeDescription: 'string' },
  },
  ProjectionRebuilt: {
    schemaV: 1,
    producer: 'Projections',
    consumers: ['Health'],
    idempotentBy: null,
    fields: { projectorId: 'string', toWatermark: 'number', durationMs: 'number' },
  },
} as const;

export type EventTypeName = keyof typeof EVENT_REGISTRY;
